In [1]:
# importando bibliotecas

import pandas as pd
import numpy as np

In [3]:
# importando dataset

fifa19 = pd.read_csv(r'fifa19.csv')
fifa19

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,18202,238813,J. Lundstram,19,https://cdn.sofifa.org/players/4/19/238813.png,England,https://cdn.sofifa.org/flags/14.png,47,65,Crewe Alexandra,...,45.0,40.0,48.0,47.0,10.0,13.0,7.0,8.0,9.0,€143K
18203,18203,243165,N. Christoffersson,19,https://cdn.sofifa.org/players/4/19/243165.png,Sweden,https://cdn.sofifa.org/flags/46.png,47,63,Trelleborgs FF,...,42.0,22.0,15.0,19.0,10.0,9.0,9.0,5.0,12.0,€113K
18204,18204,241638,B. Worman,16,https://cdn.sofifa.org/players/4/19/241638.png,England,https://cdn.sofifa.org/flags/14.png,47,67,Cambridge United,...,41.0,32.0,13.0,11.0,6.0,5.0,10.0,6.0,13.0,€165K
18205,18205,246268,D. Walker-Rice,17,https://cdn.sofifa.org/players/4/19/246268.png,England,https://cdn.sofifa.org/flags/14.png,47,66,Tranmere Rovers,...,46.0,20.0,25.0,27.0,14.0,6.0,14.0,8.0,9.0,€143K
18206,18206,246269,G. Nugent,16,https://cdn.sofifa.org/players/4/19/246269.png,England,https://cdn.sofifa.org/flags/14.png,46,66,Tranmere Rovers,...,43.0,40.0,43.0,50.0,10.0,15.0,9.0,12.0,9.0,€165K

In [4]:
# criando a tabela dinâmica com a metrica média

# sintaxe: pd.pivot_table(dataset, index=, aggfunc=)

fifa19_filtrado = fifa19[fifa19['Nationality'].isin(['Argentina', 'Brazil', 'France', 'Germany', 'Italy'])]
pd.pivot_table(fifa19_filtrado, index='Nationality', aggfunc = np.mean)

<ipython-input-4-e885355bd083>:6: FutureWarning: The operation <function mean at 0x00000272392C20D0> failed on a column. If any error is raised, this will raise an exception in a future version of pandas. Drop these columns to avoid this warning.
  pd.pivot_table(fifa19_filtrado, index='Nationality', aggfunc = np.mean)

,Acceleration,Age,Aggression,Agility,Balance,BallControl,Composure,Crossing,Curve,Dribbling,...,SlidingTackle,Special,SprintSpeed,Stamina,StandingTackle,Strength,Unnamed: 0,Vision,Volleys,Weak Foot
Nationality,,,,,,,,,,,,,,,,,,,,,
Argentina,64.625000,26.205977,56.725427,64.193376,64.376068,60.808761,60.452991,51.319444,48.883547,58.068376,...,46.340812,1639.410886,64.318376,64.162393,47.970085,65.561966,7285.958378,54.862179,44.863248,2.870726
Brazil,66.318788,27.625151,59.972121,65.201212,63.966061,63.841212,65.241212,54.699394,53.403636,60.850909,...,48.981818,1712.134220,66.701818,65.675152,51.284848,67.263030,5141.252721,58.113939,49.918788,2.945455
France,64.524698,24.615974,56.958288,62.819978,63.919868,59.787047,60.586169,51.739846,47.963776,56.736553,...,48.156970,1624.257112,64.714599,62.648738,50.047201,66.480790,8075.863239,54.236004,43.468716,2.915477
Germany,63.287029,24.338063,55.931381,62.354812,61.830126,56.675314,56.370711,48.337238,45.133054,53.167364,...,45.204184,1566.782972,63.690377,62.600000,47.620084,66.953975,9392.902337,51.120502,41.038494,3.133891
Italy,63.167382,25.928775,55.429185,63.065808,62.858369,59.224607,62.530758,49.763948,47.859800,55.350501,...,46.669528,1604.572650,63.341917,62.426323,48.359084,65.114449,7621.792023,51.652361,44.390558,2.846924

In [5]:
# criando a tabela dinamica com a metrica mediana

pd.pivot_table(fifa19_filtrado, index='Nationality', aggfunc= np.median)

<ipython-input-5-0c3cf8e49773>:3: FutureWarning: The operation <function median at 0x00000272393E5820> failed on a column. If any error is raised, this will raise an exception in a future version of pandas. Drop these columns to avoid this warning.
  pd.pivot_table(fifa19_filtrado, index='Nationality', aggfunc= np.median)

,Acceleration,Age,Aggression,Agility,Balance,BallControl,Composure,Crossing,Curve,Dribbling,...,SlidingTackle,Special,SprintSpeed,Stamina,StandingTackle,Strength,Unnamed: 0,Vision,Volleys,Weak Foot
Nationality,,,,,,,,,,,,,,,,,,,,,
Argentina,68.0,26,60.0,66.0,66.0,65.0,61.0,56.0,50.0,64.0,...,53.0,1677,67.0,67.0,53.0,67.0,6276.0,57.0,46.0,3.0
Brazil,68.0,27,63.0,68.0,66.0,69.0,66.0,60.0,57.0,67.0,...,56.0,1759,69.0,68.0,60.0,68.0,4391.0,60.0,53.0,3.0
France,67.0,24,60.0,65.0,65.0,64.0,61.0,56.0,50.0,62.0,...,58.0,1657,67.0,66.0,60.0,67.0,7479.5,56.0,44.0,3.0
Germany,66.0,24,60.0,66.0,65.0,62.0,58.0,53.0,46.0,59.0,...,53.0,1606,67.0,66.0,56.0,68.0,9804.5,52.0,42.0,3.0
Italy,67.0,26,60.0,65.0,65.0,65.0,63.0,56.0,52.0,62.0,...,57.0,1650,67.0,67.0,58.0,66.0,7114.5,54.0,47.0,3.0

In [6]:
# criando uma nova pivot table com as colunas: 'Age', 'Overall', 'Acceleration' e 
#o index sendo a coluna 'Nationality'

pd.pivot_table(fifa19_filtrado, index='Nationality',
              values=['Age', 'Overall', 'Acceleration'],
              aggfunc = np.median)

             Acceleration  Age  Overall
Nationality
Argentina            68.0   26       69
Brazil               68.0   27       71
France               67.0   24       68
Germany              66.0   24       66
Italy                67.0   26       68

In [7]:
# criando uma nova pivot table com dois index 'Nationality', 'Club' e gerando um 
# arquivo .CSV

pivot_table = pd.pivot_table(fifa19_filtrado, index=['Nationality','Club'],
              values=['Age', 'Overall', 'Acceleration'],
              aggfunc = np.median)

pivot_table.to_csv('pivot_table.csv', sep=';', decimal=',')

# o arquivo estara dentro da pasta onde está localizado o .ipynb

In [9]:
# um outro exemplo de pivot table com o campo columns ='Position'

pd.pivot_table(fifa19_filtrado, index=['Nationality', 'Club'],
              values=['Age', 'Overall', 'Acceleration'],
              columns='Position',
              aggfunc = np.median)

                                Acceleration                                  \
Position                                 CAM    CB   CDM  CF    CM    GK LAM
Nationality Club
Argentina   AD Alcorcón                  NaN   NaN   NaN NaN   NaN   NaN NaN
            AEK Athens                   NaN   NaN   NaN NaN   NaN   NaN NaN
            AIK                          NaN   NaN   NaN NaN   NaN   NaN NaN
            AJ Auxerre                   NaN   NaN   NaN NaN  66.0   NaN NaN
            Ajax                         NaN   NaN   NaN NaN   NaN   NaN NaN
...                                      ...   ...   ...  ..   ...   ...  ..
Italy       Sheffield Wednesday          NaN   NaN   NaN NaN   NaN   NaN NaN
            Spezia                      67.0  49.5   NaN NaN  64.0  35.0 NaN
            Tranmere Rovers              NaN   NaN   NaN NaN   NaN   NaN NaN
            Venezia FC                   NaN  55.0  63.0 NaN  64.5  46.0 NaN
            Waasland-Beveren             NaN   NaN   NaN NaN   NaN   NaN NaN

                                                   ... Overall              \
Position                           LB   LCB   LCM  ...      RB   RCB   RCM
Nationality Club                                   ...
Argentina   AD Alcorcón           NaN   NaN   NaN  ...     NaN  68.0   NaN
            AEK Athens            NaN   NaN   NaN  ...     NaN   NaN   NaN
            AIK                   NaN   NaN   NaN  ...     NaN   NaN   NaN
            AJ Auxerre            NaN   NaN   NaN  ...     NaN   NaN   NaN
            Ajax                 85.0   NaN   NaN  ...     NaN   NaN   NaN
...                               ...   ...   ...  ...     ...   ...   ...
Italy       Sheffield Wednesday   NaN   NaN   NaN  ...     NaN   NaN   NaN
            Spezia               73.0  56.0  79.0  ...    67.0  72.0  69.0
            Tranmere Rovers       NaN   NaN   NaN  ...     NaN   NaN   NaN
            Venezia FC           72.0  61.0  73.0  ...     NaN  65.0  70.0
            Waasland-Beveren      NaN   NaN   NaN  ...     NaN   NaN   NaN


Position                        RDM  RF    RM    RS    RW RWB    ST
Nationality Club
Argentina   AD Alcorcón         NaN NaN   NaN   NaN   NaN NaN   NaN
            AEK Athens          NaN NaN   NaN   NaN   NaN NaN  72.0
            AIK                 NaN NaN   NaN   NaN   NaN NaN  67.0
            AJ Auxerre          NaN NaN   NaN   NaN   NaN NaN   NaN
            Ajax                NaN NaN   NaN   NaN   NaN NaN   NaN
...                              ..  ..   ...   ...   ...  ..   ...
Italy       Sheffield Wednesday NaN NaN   NaN   NaN   NaN NaN  74.0
            Spezia              NaN NaN   NaN   NaN  61.0 NaN   NaN
            Tranmere Rovers     NaN NaN   NaN   NaN   NaN NaN  57.0
            Venezia FC          NaN NaN  64.0  68.0   NaN NaN  67.0
            Waasland-Beveren    NaN NaN   NaN  65.0   NaN NaN   NaN

[834 rows x 81 columns]

In [11]:
# um outro exemplo de pivot table com o campo columns ='Club'

pd.pivot_table(fifa19_filtrado, index=['Nationality'],
              values=['Age', 'Overall', 'Acceleration'],
              columns='Club',
              aggfunc= np.median)

                    Acceleration                                             \
Club         SSV Jahn Regensburg 1. FC Heidenheim 1846 1. FC Kaiserslautern
Nationality
Argentina                    NaN                   NaN                  NaN
Brazil                       NaN                   NaN                  NaN
France                       NaN                   NaN                  NaN
Germany                     65.0                  67.0                 64.0
Italy                        NaN                   NaN                  NaN

                                                                          \
Club        1. FC Köln 1. FC Magdeburg 1. FC Nürnberg 1. FC Union Berlin
Nationality
Argentina          NaN             NaN            NaN                NaN
Brazil             NaN             NaN           66.5                NaN
France            74.5            61.0            NaN                NaN
Germany           67.0            64.5           64.5               65.0
Italy              NaN             NaN            NaN                NaN

                                                   ...   Overall              \
Club        1. FSV Mainz 05 AC Ajaccio AC Horsens  ... Willem II Wisła Płock
Nationality                                        ...
Argentina               NaN        NaN        NaN  ...       NaN         NaN
Brazil                  NaN        NaN        NaN  ...       NaN        66.0
France                 69.0       64.5        NaN  ...      64.0         NaN
Germany                66.5        NaN        NaN  ...      68.0        63.0
Italy                  68.0        NaN       68.0  ...       NaN         NaN

                                                                     \
Club        Wolfsberger AC Wolverhampton Wanderers Yeni Malatyaspor
Nationality
Argentina              NaN                     NaN              NaN
Brazil                 NaN                    73.0             73.0
France                 NaN                    77.0             69.0
Germany               69.0                     NaN             72.0
Italy                  NaN                     NaN              NaN

                                                                \
Club        Yeovil Town Yokohama F. Marinos Zagłębie Sosnowiec
Nationality
Argentina           NaN                 NaN                NaN
Brazil             60.0                68.0               59.0
France             62.0                 NaN               64.0
Germany             NaN                 NaN               64.0
Italy              54.0                 NaN                NaN


Club        Çaykur Rizespor Örebro SK
Nationality
Argentina               NaN       NaN
Brazil                 71.0      58.0
France                 58.0       NaN
Germany                68.5       NaN
Italy                  68.0       NaN

[5 rows x 1526 columns]